# Default boot preset for GeminiOS.
# Lines add services to the boot set.
# Prefix a name with "-" in /etc/ginit/boot-services.conf to remove it.

udevd
udev-trigger
udev-settle
swap-activate
fuse-device
network
dbus
elogind
